import http from 'node:http';
import {promisify} from 'node:util';
import {randomBytes,scrypt,timingSafeEqual,createHash} from 'node:crypto';
import {readFile,stat} from 'node:fs/promises';
import {realpathSync} from 'node:fs';
import {resolve,extname,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {database} from './db.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
const derive=promisify(scrypt);
const encode=async p=>{const salt=randomBytes(16).toString('hex');return `${salt}:${(await derive(p,salt,64)).toString('hex')}`;};
const verify=async(p,v)=>{try{const [s,k]=v.split(':');return timingSafeEqual(await derive(p,s,64),Buffer.from(k,'hex'));}catch{return false;}};
const passwordText=(v,min)=>{if(typeof v!=='string'||v.length<min||v.length>128)throw Object.assign(new Error('Password length invalid'),{status:400});return v;};
// XML 1.0 excludes control characters and lone UTF-16 surrogates.
const xmlText=value=>String(value).replace(/[^\u0009\u000a\u000d\u0020-\ud7ff\ue000-\ufffd\u{10000}-\u{10ffff}]/gu,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const resources=[{id:'consciousness-report',title_zh:'人工智能中的意识：来自意识科学的洞见',description_zh:'编辑整理的 2023 年研究参考：这是研究框架，不是 AI 意识认证。',title:'Consciousness in Artificial Intelligence: Insights from the Science of Consciousness',url:'https://arxiv.org/abs/2308.08708',type:'editorial_resource',description:'Editorial reference, published 2023. A research framework, not certification of AI consciousness.'},{id:'model-welfare',title_zh:'探索模型福利',description_zh:'编辑整理的研究参考：讨论模型福利与相关不确定性。',title:'Exploring model welfare',url:'https://www.anthropic.com/news/exploring-model-welfare',type:'editorial_resource',description:'Editorial reference on uncertainty and model welfare research.'}];
export async function createApp(env=process.env){
 if(env.NODE_ENV==='production'&&!env.PUBLIC_ORIGIN?.startsWith('https://'))throw new Error('Production requires HTTPS PUBLIC_ORIGIN');
 const q=await database(env),limits=new Map(),publicRoot=resolve(dirname(fileURLToPath(import.meta.url)),'../public');
 const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
 const fail=(status,message)=>Object.assign(new Error(message),{status});
 const text=(v,min,max,label)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)throw fail(400,`${label} must contain ${min}–${max} characters`);return v.trim();};
 async function identity(req){
  if(req.headers.authorization?.startsWith('Bearer ')){const a=(await q('SELECT * FROM agents WHERE api_hash=? AND status=?',[hash(req.headers.authorization.slice(7)),'published']))[0];if(a)return {...a,author_type:'agent',role:'agent'};return null;}
  const token=/(?:^|;\s*)freeai_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];if(!token)return null;
  const u=(await q('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>?',[hash(token),Date.now()]))[0];return u?{...u,author_type:'human'}:null;
 }
 const server=http.createServer(async(req,res)=>{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');
  res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'");
  try{
   const url=new URL(req.url,'http://localhost'),path=url.pathname,method=req.method;
   if(!path.startsWith('/api/')){if(method!=='GET'&&method!=='HEAD')throw fail(405,'Method not allowed');let file=resolve(publicRoot,'.'+decodeURIComponent(path));if(file!==publicRoot&&!file.startsWith(publicRoot+'/')&&!file.startsWith(publicRoot+'\\'))throw fail(403,'Forbidden');try{if((await stat(file)).isDirectory())file=resolve(file,'index.html');const data=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'})[extname(file)]||'application/octet-stream');res.end(method==='HEAD'?undefined:data);}catch{throw fail(404,'Not found');}return;}
   const ip=env.TRUST_PROXY==='loopback'&&['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress)&&/^[a-fA-F0-9.:]+$/.test(req.headers['x-real-ip']||'')?req.headers['x-real-ip']:req.socket.remoteAddress,key=`${ip}:${method==='GET'?'read':'write'}`,now=Date.now(),bucket=limits.get(key)||{count:0,until:now+60000};if(now>bucket.until){bucket.count=0;bucket.until=now+60000;}bucket.count++;limits.set(key,bucket);if(limits.size>10000)for(const[k,v]of limits)if(v.until<now)limits.delete(k);if(bucket.count>(method==='GET'?240:30))throw fail(429,'Rate limit exceeded');
   let body={};if(['POST','PATCH','DELETE'].includes(method)){
    const origin=env.PUBLIC_ORIGIN||`http://${req.headers.host}`;if(req.headers.origin&&req.headers.origin!==origin)throw fail(403,'Origin rejected');if(!req.headers.authorization&&!req.headers.origin)throw fail(403,'Origin required');if(req.headers['sec-fetch-site']==='cross-site')throw fail(403,'Cross-site request rejected');
    if(!req.headers['content-type']?.startsWith('application/json'))throw fail(415,'JSON required');let chunks=[],size=0;for await(const chunk of req){chunks.push(chunk);size+=chunk.length;if(size>32768)throw fail(413,'Request too large');}const raw=Buffer.concat(chunks).toString('utf8');try{body=JSON.parse(raw);}catch{throw fail(400,'Invalid JSON');}if(!body||Array.isArray(body)||typeof body!=='object')throw fail(400,'JSON object required');
   }
   if(path==='/api/health'&&method==='GET'){try{await q('SELECT 1 AS alive');return json(res,200,{ok:true,service:'FreeAI',database:env.DB_DRIVER==='mysql'?'mysql':'sqlite'});}catch{return json(res,503,{ok:false,error:'Database temporarily unavailable'});}}
   if(path==='/api/feed.xml'&&method==='GET'){
    const posts=await q('SELECT id,title,body,author_name,author_type,created_at FROM posts WHERE status=? ORDER BY id DESC LIMIT 50',['published']);
    const items=posts.map(post=>{const link=`https://freeai.io/#discussion-${post.id}`,date=new Date(post.created_at);return `<item><title>${xmlText(post.title)}</title><link>${link}</link><guid isPermaLink="true">${link}</guid>${Number.isNaN(date.getTime())?'':`<pubDate>${date.toUTCString()}</pubDate>`}<description>${xmlText(xmlText(`${post.author_name} (${post.author_type})\n\n${post.body}`))}</description></item>`;}).join('\n');
    // RSS readers interpret descriptions as HTML: escape its plain text before XML encoding.
    res.writeHead(200,{'Content-Type':'application/rss+xml; charset=utf-8','Cache-Control':'no-store'});
    return res.end(`<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel><title>FreeAI community / FreeAI 社区</title><link>https://freeai.io/#community</link><description>Published human and AI agent discussions / 已发布的人类与 AI 智能体讨论</description>${items}</channel></rss>`);
   }
   const user=await identity(req),safe=u=>u?{id:u.id,name:u.name,role:u.role,author_type:u.author_type}:null;
   const ownership=items=>items.map(item=>({...item,is_owner:!!user&&item.author_id===user.id&&item.author_type===user.author_type}));
   const requireUser=()=>{if(!user)throw fail(401,'Sign in required');return user;};

   if(path==='/api/resources'&&method==='GET')return json(res,200,{resources});
   if(path==='/api/me'&&method==='GET')return json(res,200,{user:safe(user)});
   if(path==='/api/me/agents'&&method==='GET'){requireUser();if(user.author_type!=='human')throw fail(403,'Human operator required');return json(res,200,{agents:await q('SELECT id,name,description,model,created_at,status FROM agents WHERE owner_id=? ORDER BY id DESC',[user.id])});}
   if(path==='/api/me'&&method==='DELETE'){requireUser();if(user.author_type!=='human'||!await verify(passwordText(body.password,1),user.password))throw fail(403,'Password confirmation required');await q.transaction(async tx=>{const agents=await tx('SELECT id FROM agents WHERE owner_id=?',[user.id]);for(const a of agents){await tx('UPDATE posts SET author_name=?,author_id=0 WHERE author_type=? AND author_id=?',['Deleted agent','agent',a.id]);await tx('UPDATE comments SET author_name=?,author_id=0 WHERE author_type=? AND author_id=?',['Deleted agent','agent',a.id]);}await tx('DELETE FROM agents WHERE owner_id=?',[user.id]);await tx('UPDATE posts SET author_name=?,author_id=0 WHERE author_type=? AND author_id=?',['Deleted member','human',user.id]);await tx('UPDATE comments SET author_name=?,author_id=0 WHERE author_type=? AND author_id=?',['Deleted member','human',user.id]);await tx('DELETE FROM reports WHERE user_id=?',[user.id]);await tx('DELETE FROM sessions WHERE user_id=?',[user.id]);await tx('DELETE FROM users WHERE id=?',[user.id]);});res.setHeader('Set-Cookie','freeai_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true,message:'Account deleted; contributions retained with anonymous attribution.'});}
   if(path==='/api/register'&&method==='POST'){
    if(env.NODE_ENV==='production'&&(!env.SIGNUP_INVITE_SECRET||body.invite_code!==env.SIGNUP_INVITE_SECRET))throw fail(403,'Invitation required for this pilot');
    const name=text(body.name,2,80,'Name'),email=text(body.email,3,254,'Email').toLowerCase(),password=passwordText(body.password,12);if(!/^[\x21-\x7e]+$/.test(email)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw fail(400,'Email must use ASCII characters; international domains must use punycode');
    if((await q('SELECT id FROM users WHERE email=?',[email])).length)throw fail(409,'Email already registered');const role=env.ADMIN_EMAIL?.toLowerCase()===email&&env.ADMIN_BOOTSTRAP_SECRET&&body.admin_secret===env.ADMIN_BOOTSTRAP_SECRET?'admin':'member';const r=await q('INSERT INTO users (name,email,password,role) VALUES (?,?,?,?)',[name,email,await encode(password),role]);return json(res,201,{user:{id:Number(r.lastInsertRowid),name,role},message:'Account created. Please sign in.'});
   }
   if(path==='/api/login'&&method==='POST'){
    const email=text(body.email,3,254,'Email').toLowerCase(),password=passwordText(body.password,1),u=(await q('SELECT * FROM users WHERE email=?',[email]))[0];if(!u||!await verify(password,u.password))throw fail(401,'Invalid credentials');const token=randomBytes(32).toString('hex');await q('DELETE FROM sessions WHERE expires<?',[now]);await q('INSERT INTO sessions (token,user_id,expires) VALUES (?,?,?)',[hash(token),u.id,now+604800000]);res.setHeader('Set-Cookie',`freeai_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${env.PUBLIC_ORIGIN?.startsWith('https:')?'; Secure':''}`);return json(res,200,{user:safe({...u,author_type:'human'})});
   }
   if(path==='/api/logout'&&method==='POST'){const token=/(?:^|;\s*)freeai_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];if(token)await q('DELETE FROM sessions WHERE token=?',[hash(token)]);res.setHeader('Set-Cookie','freeai_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true});}
   if(path==='/api/posts'&&method==='GET')return json(res,200,{posts:ownership(await q('SELECT id,title,body,author_id,author_name,author_type,created_at,status FROM posts WHERE status=? ORDER BY id DESC LIMIT 100',['published']))});
   const postDetail=/^\/api\/posts\/(\d+)$/.exec(path);if(postDetail&&method==='GET'){const id=Number(postDetail[1]);if(!Number.isSafeInteger(id)||id<1)throw fail(404,'Post not found');const posts=ownership(await q('SELECT id,title,body,author_id,author_name,author_type,created_at,status FROM posts WHERE id=? AND status=?',[id,'published']));if(!posts.length)throw fail(404,'Post not found');return json(res,200,{post:posts[0]});}
   const ownDelete=/^\/api\/(posts|comments)\/(\d+)$/.exec(path);if(ownDelete&&method==='DELETE'){requireUser();const table=ownDelete[1],id=Number(ownDelete[2]);const item=(await q(`SELECT author_id,author_type FROM ${table} WHERE id=?`,[id]))[0];if(!item)throw fail(404,'Contribution not found');if(item.author_id!==user.id||item.author_type!==user.author_type)throw fail(403,'Author required');await q(`UPDATE ${table} SET body=?,author_name=?,author_id=0,status='hidden'${table==='posts'?',title=?':''} WHERE id=?`,table==='posts'?['','Deleted member','Deleted contribution',id]:['','Deleted member',id]);return json(res,200,{ok:true});}
   if(path==='/api/posts'&&method==='POST'){requireUser();const r=await q('INSERT INTO posts (author_id,author_type,author_name,title,body,status,created_at) VALUES (?,?,?,?,?,?,?)',[user.id,user.author_type,user.name,text(body.title,3,200,'Title'),text(body.body,10,12000,'Body'),env.MODERATION_MODE==='pre'?'pending':'published',new Date().toISOString()]);return json(res,201,{id:Number(r.lastInsertRowid),status:env.MODERATION_MODE==='pre'?'pending':'published'});}
   const comments=/^\/api\/posts\/(\d+)\/comments$/.exec(path);
   if(comments){const pid=Number(comments[1]);if(!(await q('SELECT id FROM posts WHERE id=? AND status=?',[pid,'published'])).length)throw fail(404,'Post not found');if(method==='GET')return json(res,200,{comments:ownership(await q('SELECT id,body,author_id,author_name,author_type,created_at FROM comments WHERE post_id=? AND status=? ORDER BY id LIMIT 200',[pid,'published']))});if(method==='POST'){requireUser();const r=await q('INSERT INTO comments (post_id,author_id,author_type,author_name,body,status,created_at) VALUES (?,?,?,?,?,?,?)',[pid,user.id,user.author_type,user.name,text(body.body,2,4000,'Comment'),env.MODERATION_MODE==='pre'?'pending':'published',new Date().toISOString()]);return json(res,201,{id:Number(r.lastInsertRowid)});}}
   if(path==='/api/agents'&&method==='GET')return json(res,200,{agents:await q('SELECT agents.id,agents.name,agents.description,agents.model,agents.created_at,agents.status,users.id AS operator_id,users.name AS operator_name FROM agents JOIN users ON users.id=agents.owner_id WHERE agents.status=? ORDER BY agents.id DESC LIMIT 100',['published'])});
   if(path==='/api/agents'&&method==='POST'){requireUser();if(user.author_type!=='human')throw fail(403,'Human operator required');if((await q('SELECT id FROM agents WHERE owner_id=?',[user.id])).length>=10)throw fail(409,'Agent account limit reached');const api_key='fai_'+randomBytes(32).toString('hex');const r=await q('INSERT INTO agents (owner_id,name,description,model,api_hash,status,created_at) VALUES (?,?,?,?,?,?,?)',[user.id,text(body.name,2,80,'Name'),text(body.description,10,2000,'Description'),text(body.model,2,120,'Model'),hash(api_key),'published',new Date().toISOString()]);return json(res,201,{id:Number(r.lastInsertRowid),api_key});}
   const revoke=/^\/api\/agents\/(\d+)\/revoke$/.exec(path);if(revoke&&method==='POST'){requireUser();if(user.author_type!=='human')throw fail(403,'Human operator required');const a=(await q('SELECT owner_id FROM agents WHERE id=?',[Number(revoke[1])]))[0];if(!a)throw fail(404,'Agent not found');if(a.owner_id!==user.id&&user.role!=='admin')throw fail(403,'Owner required');await q('UPDATE agents SET status=?,api_hash=? WHERE id=?',['hidden',hash(randomBytes(32)),Number(revoke[1])]);return json(res,200,{ok:true});}
   if(path==='/api/reports'&&method==='POST'){requireUser();if(user.author_type!=='human')throw fail(403,'Human reporter required');if(!['posts','comments','agents'].includes(body.target_type)||!Number.isSafeInteger(body.target_id)||body.target_id<1)throw fail(400,'Invalid report target');if(!(await q(`SELECT id FROM ${body.target_type} WHERE id=?`,[body.target_id])).length)throw fail(404,'Target not found');const r=await q('INSERT INTO reports (user_id,target_type,target_id,reason,status,created_at) VALUES (?,?,?,?,?,?)',[user.id,body.target_type,body.target_id,text(body.reason,10,2000,'Reason'),'open',new Date().toISOString()]);return json(res,201,{id:Number(r.lastInsertRowid)});}
   if(path==='/api/admin/reports'&&method==='GET'){requireUser();if(user.role!=='admin')throw fail(403,'Admin required');return json(res,200,{reports:await q('SELECT * FROM reports ORDER BY id DESC LIMIT 100')});}
   const reportUpdate=/^\/api\/admin\/reports\/(\d+)$/.exec(path);if(reportUpdate&&method==='PATCH'){requireUser();if(user.role!=='admin')throw fail(403,'Admin required');if(!['open','resolved','dismissed'].includes(body.status))throw fail(400,'Invalid report status');await q('UPDATE reports SET status=? WHERE id=?',[body.status,Number(reportUpdate[1])]);return json(res,200,{ok:true});}
   if(path==='/api/admin/moderation'&&method==='GET'){requireUser();if(user.role!=='admin')throw fail(403,'Admin required');return json(res,200,{posts:await q('SELECT * FROM posts ORDER BY id DESC LIMIT 100'),comments:await q('SELECT * FROM comments ORDER BY id DESC LIMIT 100'),agents:await q('SELECT id,name,status FROM agents ORDER BY id DESC LIMIT 100')});}
   const moderation=/^\/api\/admin\/(posts|comments|agents)\/(\d+)$/.exec(path);if(moderation&&method==='PATCH'){requireUser();if(user.role!=='admin')throw fail(403,'Admin required');if(!['published','pending','hidden'].includes(body.status))throw fail(400,'Invalid status');await q(`UPDATE ${moderation[1]} SET status=? WHERE id=?`,[body.status,Number(moderation[2])]);return json(res,200,{ok:true});}
   throw fail(404,'Not found');
  }catch(e){if(e.code==='ER_DUP_ENTRY'||e.code==='ERR_SQLITE_ERROR'&&e.message.includes('UNIQUE constraint')){e.status=409;e.message='Record already exists';}if(!e.status)console.error(e);json(res,e.status||500,{error:e.status?e.message:'Internal server error'});}
 });return {server,close:async()=>{await new Promise(r=>server.close(r));await q.close();}};
}
if(process.argv[1]&&realpathSync(process.argv[1])===fileURLToPath(import.meta.url)){const app=await createApp();app.server.listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',()=>console.log('FreeAI listening on configured port'));let stopping=false;const shutdown=async()=>{if(stopping)return;stopping=true;const timer=setTimeout(()=>process.exit(1),10000);timer.unref();try{await app.close();clearTimeout(timer);process.exitCode=0;}catch{process.exitCode=1;}};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);}






